nginx:
    build: ./nginx
    links:
        - node1:node1
        - node2:node2
        - node3:node3
    ports:
        - "80:80"
node1:
    build: ./node
    links:
        - redis
    ports:
        - "8090:3333"
node2:
    build: ./node
    links:
        - redis
    ports:
        - "8091:3333"
node3:
    build: ./node
    links:
        - redis
    ports:
        - "8092:3333"
redis:
    image: redis:3-alpine
    ports:
        - "6379:6379"
